http_server:
  host: 127.0.0.1
postgres:
  database_name: rust-kata-003
  host: 127.0.0.1
  password: password
  username: postgres
  require_ssl: false
redis:
  database: 0
  host: 127.0.0.1
  ssl: false
