name: Security Audit

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  push:
    branches:
      - main
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"

env:
  CARGO_TERM_COLOR: always

jobs:
  security_audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
